version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - database
      
  database:
    image: postgres
    container_name: postegres
    restart: always
    environment:
      - POSTGRES_USER=neoway
      - POSTGRES_PASSWORD=neoway
      - POSTGRES_NAME=dbneoway
    ports:
      - "5432:5432"
    volumes:
      - ./data/database:/var/lib/postgresql/data